// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmWFTsC-xMoCjZnuri3jptUUov56TaPtI',
    appId: '1:1019089180601:web:8bc5c9955b0ce6b1f5c868',
    messagingSenderId: '1019089180601',
    projectId: 'castonaut',
    authDomain: 'castonaut.firebaseapp.com',
    storageBucket: 'castonaut.appspot.com',
    measurementId: 'G-L6W0DDG3MJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHrCHeeNyumDjj5QbgFaUYTdQMmc1Moac',
    appId: '1:1019089180601:android:3872d2d6a7fa860bf5c868',
    messagingSenderId: '1019089180601',
    projectId: 'castonaut',
    storageBucket: 'castonaut.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiKYMh3zur-M2IHDnfU7GLAfLfZhG9J6Y',
    appId: '1:1019089180601:ios:5b60f3798c710032f5c868',
    messagingSenderId: '1019089180601',
    projectId: 'castonaut',
    storageBucket: 'castonaut.appspot.com',
    androidClientId: '1019089180601-plu325cioe0o50lmudnjtanlp0of0vnh.apps.googleusercontent.com',
    iosClientId: '1019089180601-u8g7qb82dqhvavkh92uaokn1qqjdphpo.apps.googleusercontent.com',
    iosBundleId: 'com.ashanti.castonaut',
  );
}
